server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lab4
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: create-drop
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-main.yaml